# Generated by Django 5.1.3 on 2024-11-23 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cita_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='especialidad',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
